### ISSUE TITLE
[Feature request] Silent mode

### ISSUE THREAD

**Issue by man3kin3ko** [blacklanternsecurity/baddns#478]
Can I ask you for adding a silent mode feature (only vulnerable domains in the output)? Thanks

**Comment by liquidsec** [comment]
See your PR (https://github.com/blacklanternsecurity/baddns/pull/479) for discussion

**Comment by liquidsec** [comment]
Being added in https://github.com/blacklanternsecurity/baddns/pull/484, with some modifications
